- hosts: k8s_workers
  gather_facts: no
  tasks:
    - block:
        - name: "Retrieve kafka properties"
          fetch:
            src: /opt/pv-kafka-kafka/data/meta.properties
            dest: /tmp
          register: fetched_file
        - name: "Retrieve zookeeper id"
          slurp:
            src: /opt/pv-zookeeper-kafka/data/myid
          register: zookeeper_id_file
        - name: "Store zookeeper id"
          set_fact:
            broker_id: |-
              {{
                lookup(
                  'ini',
                  'broker.id type=properties file=' ~ fetched_file.dest,
                )
              }}
            zookeeper_id: "{{ (zookeeper_id_file.content | b64decode).replace('\n', '') }}"

- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - vars:
        zookeeper_pods : |
          {{
            lookup(
              'kubernetes.core.k8s',
              namespace='kafka',
              kind='pod',
              label_selector='app.kubernetes.io/name=zookeeper'
            )
          }}
        kafka_pods : |
          {{
            lookup(
              'kubernetes.core.k8s',
              namespace='kafka',
              kind='pod',
              label_selector='app.kubernetes.io/name=kafka'
            )
          }}
      debug:
        msg: |
          {% for host in groups.k8s_workers %}
          [{{ host }}]
            broker_id     : {{ hostvars[host].broker_id }}
          {% for pod in kafka_pods | selectattr('spec.nodeName', 'equalto', host) %}
            kafka_pod     : {{ pod.metadata.name }}
          {% endfor %}

            zookeeper_id  : {{ hostvars[host].zookeeper_id }}
          {% for pod in zookeeper_pods | selectattr('spec.nodeName', 'equalto', host) %}
            zookeeper_pod : {{ pod.metadata.name }}
          {% endfor %}
          {% endfor %}

