heapOpts: -Xmx512m -Xms512m
replicaCount: 3
persistence:
  enabled: false
resources:
  limits:
    memory: 768Mi
    cpu: 1
  requests:
    memory: 768Mi
    cpu: 10m
zookeeper:
  enabled: true
  heapOpts: -Xmx512m -Xms512m
  replicaCount: 3
  persistence:
    enabled: false
  resources:
    limits:
      memory: 768Mi
      cpu: 1
    requests:
      memory: 768Mi
      cpu: 10m
